### ISSUE TITLE
Google import 

### ISSUE THREAD

**Issue by htuch** [envoyproxy/nighthawk#119]
There are a number of things we need to ensure we can cleanly import Nighthawk into Google:
* [x] service_main.cc needs to be able to handle IPv6 addresses. Its test, `service_main_test.cc`, should work with `TestEnvironment::getIpVersionsForTest`.
* [x] service_test.cc and process_test.cc also need to consume from `TestEnvironment::getIpVersionsForTest` when forming loopback addresses.
* [x] We need to switch Envoy import paths from overlay to `external/envoy` based and structurally enforce this.
* [x] We need to eliminate the race being fixed in https://github.com/envoyproxy/nighthawk/pull/118

**Comment by oschaaf** [comment]
I have been looking getting the include path overlay fixed.
There now is a candidate script to test for this: https://github.com/envoyproxy/nighthawk/pull/122, but unfortunately updating the include paths as planned causes the build to fail.

**Comment by oschaaf** [comment]
status update: 
- the fix for the observed race in the service is in review, pending discussion.
- maybe we should brainstorm on slack to see if we can come up with a plan B for disambiguating the Envoy include paths; the script to check for what we do not want to see is implemented, but actually updating the include paths doesn't seem to work for me (see the comment above).
- I'll look into getting the ipv6 handling sorted tomorrow.
