### ISSUE TITLE
Use `map` instead of JSON-object format for Counters

### ISSUE THREAD

**Issue by nareddyt** [envoyproxy/nighthawk#169]
https://github.com/envoyproxy/nighthawk/blob/267fb598a31bc6f95e6a0e3bb56bd5287f01b434/api/client/output.proto#L32

Instead of creating a separate `Counter` object that only contains key/value pairs, the field above can be rewritten using a map.

```
map<string, uint64> counters = 3;
```

This would make the output-transform code cleaner, since it can just reference a counter directly instead of searching all the counters for a specific name.

Wondering if there was any reason for not using a map at first. Is it too late to switch? (This would change the output format)

**Comment by oschaaf** [comment]
I'd be +1 on switching if it won't cause too much of a hassle for others, @htuch wdyt?

**Comment by htuch** [comment]
Sure, makes sense.

**Comment by mum4k** [comment]
One thing to note, the ordering of a map<> field is undefined. Will that complicate the life of the clients? Will that complicate unit testing?

Taking this from the other side - since this was already defined using a custom key/value implementation, what is our motivation for changing it?

**Comment by nareddyt** [comment]
Good point, I haven't considered the implications of this on clients that operate on the NH output directly.

Main reason I created this issue is because it complicates the output transformer code. For example, [these utility functions](https://github.com/envoyproxy/nighthawk/blob/52199baeb097c202fd34b9014f5aa0beaa071470/source/client/output_formatter_impl.cc#L160-L183) could be replaced with O(1) 1-liner lookups.

**Comment by mum4k** [comment]
Agreed, lookup from maps would indeed be much more efficient.

To help with a decision on this, can you indicate if these utility functions are ever called from any critical code section where the O(1) complexity would have a large impact? Or are these only used post-test to look-up results, so the change would be of a cosmetic nature?

**Comment by nareddyt** [comment]
The utility functions I shared are not for tests, they are part of the [output transform utilities](https://github.com/envoyproxy/nighthawk#nighthawk-output-transformation-utility). But they are not part of the "main" performance benchmarking suite, they are just extra utilities for clients.

[This utility function](https://github.com/envoyproxy/nighthawk/blob/52199baeb097c202fd34b9014f5aa0beaa071470/source/client/output_formatter_impl.cc#L149-L158) to get the global result is essentially `O(num-NH-workers)`, so it could be inefficient in larger performance benchmarks.

@oschaaf you may have a better idea if there are similar lookup utility functions elsewhere in the main code?

**Comment by oschaaf** [comment]
Well, the performance critical code holds direct references to any counters it wants to track so I think we're good there. I feel that if we'd have caught this earlier, it would have make sense to do this, but at this time the bar is a little higher because as this may be a breaking change with respect to our API?

If we would be up for breaking changes, then there are a couple of other things which I would bring into scope: 
- We define our own structure for counters, but probably we should just re-use Envoy's definition of that. (speaking of which, I actually wonder -- I don't remember Envoy uses a map, I think it uses `repeated` like we do)
- #115 
- #43 

#115/#43 track unifying our histograms with Envoy, and also switch `HdrHistogram` to `libcirclhist`. I think these two things can be taken on as one, because AFAICT Envoy uses `libcirclhist`. Which basically means we just need to leverage Envoy's histogram infra, like we do with counters. And then it would probably make sense to re-use it's proto api for that as well.

**Comment by mum4k** [comment]
Thank you @nareddyt for confirming that these aren't part of the main benchmark code. I think we might be arriving at a conclusion here, we all seem to agree that maps might have been a better choice to start with. However since lookups in the repeated fields aren't part of any performance critical code, this isn't a big deal at the moment, maybe just a nuisance.

On the other hand, changing this would be break the API and unless there is a lot of value from such a change, we should prefer to avoid doing that. Thank you @oschaaf for listing the other issues, so that we keep them on the radar.

Assuming I "read the room" correctly, would it be safe to assume we can close this issue?

**Comment by nareddyt** [comment]
Sounds good to me! Thanks for helping evaluate the impact

**Comment by mum4k** [comment]
Thank you @nareddyt.
