### ISSUE TITLE
Nighthawk fortio's output is discrepant then real fortio's output

### ISSUE THREAD

**Issue by kushthedude** [envoyproxy/nighthawk#514]
**Description**
Nighthawk's fortio transform output is different than real fortio output for a few fields.

#### Nighthawk's Output
```json
{
 "Labels": "",
 "RequestedQPS": 5,
 "ActualQPS": 4.9999995930000329,
 "ActualDuration": 5000000407,
 "NumThreads": 100,
 "DurationHistogram": {
  "Count": "25",
  "Data": [
   {
    "Start": 0.024088575,
    "End": 0.024088575,
    "Percent": 0,
    "Count": "1"
   },
```

#### Fortio's Output
```json
{
  "RunType": "HTTP",
  "Labels": "test",
  "StartTime": "2020-09-08T16:29:19.35507+05:30",
  "RequestedQPS": "100",
  "RequestedDuration": "5s",
  "ActualQPS": 59.9799880886016,
  "ActualDuration": 5101701580,
  "NumThreads": 8,
  "Version": "1.6.8",
  "DurationHistogram": {
    "Count": 306,
    "Min": 0.114543168,
    "Max": 0.436206912,
    "Sum": 40.422087638,
    "Avg": 0.1320983256143791,
    "StdDev": 0.03333137761133907,
    "Data": [
      {
        "Start": 0.114543168,
        "End": 0.2,
        "Percent": 97.38562091503267,
        "Count": 298
      },
```

As can be seen 
- RequestedQPS is an integer but should be a string.
- Dataentry.count, Sizes.count, HeaderSizes.count is a string but should be an integer.

**Expected Behaviour**

Nighthawk Output should be similar to Fortio's Output.

**Comment by oschaaf** [comment]
@kushthedude thanks for filing this. Part of this is duplicating https://github.com/envoyproxy/nighthawk/issues/422, but the `RequestedQPS` being serialized as an int vs as a string in NH wasn't a known issue before, and I would consider it a misdefinition on our side over at our [fortio.proto](
https://github.com/envoyproxy/nighthawk/blob/8667f7f7adf9c4fbed5872de5585e75e1c93e5b7/api/client/transform/fortio.proto#L31).

Amending `RequestedQPS` isn't hard in itself, but the challenge here is (backwards) compatibility. The same applies to the uint64 fields being serialized as strings, where Fortio serializes them as integers (brought up in the other issue mentioned above), though that is slightly harder to fix because we need to find a serializer that is willing to serialize uint64 fields as ints for us -- or switch to uint32 and raise an error when we'd detect that proceeding would result in overflows. 

We need to discuss how to best amend this; it might be that we need to define a second Fortio proto and formatter if we're going to be pedantic about it. 

/cc @dubious90 do you have any thoughts on this?
